# 私聊的CD
private_cool_time: 60
private_cool_time_switch: false
# 群属性
group_property:
  global:
    # 群共享CD
    group_cool_time: 60
    group_cool_time_switch: false
    # 群用户CD
    person_cool_time: 60
    person_cool_time_switch: false
# 黑名单用户
black_user: []
# 黑名单群
black_group: []
